const GET_ALL_CONTACT = "GET_ALl_CONTACT";
const DELETE_CONTACT = "DELETE_CONTACT";
const COUNT_PAG = "COUNT_PAG";
const COUNT_Nav = "COUNT_Nav";
export {GET_ALL_CONTACT,DELETE_CONTACT,COUNT_PAG,COUNT_Nav}