const GET_ALL_POST_CLIENT = "GET_ALL_POST_CLIENT"
const DELETE_CLIENT_CV__USERS = "DELETE_CLIENT_CV__USERS"
const SIGNLE_POST_CLIENT = "SIGNLE_POST_CLIENT"
export {GET_ALL_POST_CLIENT,DELETE_CLIENT_CV__USERS,SIGNLE_POST_CLIENT}